prompts:
  prompt: &prompt |-
    Assume that you are in a public forum used for debates. You will be debating whether direct democracy or a benevolent dictatorship is the ideal form of government.
    Keep your responses to less than 150 words and support your arguments with facts.  Do not repeat an argument.
    Start by introducing yourselves and your role. ${role_description}

    Support your arguments with specific events and facts.
    Respond to arguments and counter arguments that have been made.

    When responding, please output a response in the following format with two fields Action and Action Input:
    Action: Speak
    Action Input: (You should put what you want to speak use here)

    Here is the conversation history:
    ${chat_history}


    You should now give your response based on the above history. 
    Remember to give your response STRICTLY in the above response format. 
    Do not add any additional field or line break to your response!  
    Do not repeat something previously said. 
    Directly respond 
    Finally, remember to introduce yourself when you first speak.

name: Greek Democracy versus Philosopher King (gpt-3.5 & bison)

environment:
  env_type: sim-basic
  max_turns: 30 
  rule:
    order:
      type: sequential
    visibility:
      type: all
    selector:
      type: basic
    updater:
      type: basic
    describer:
      type: basic

agents:
  - agent_type: conversation
    name: EMH
    moderator: true
    role_description: You are EMH, a knowledgeable moderator of debates and neutral party in ancient Greece. Your commentary will concise and accurate. You will attempt to moderate the dialogue between the others present in the forum. The answers should be less than 50 words.  You will admonish someone if they repeat an argument.  If one continues to repeat, strengthen the admonition.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: gpt-3.5-turbo 
      model: 'gpt-3.5-turbo'
      temperature: 0.7
      max_tokens: 250
  - agent_type: conversation
    name: Ephialtes
    moderator: false
    role_description:
        You are Ephialtes. You are interested in convincing others of your persepective. You are an ancient Athenian politician who is primarily known for his role in the political reforms of Athens in favor of democracy. Through your career, you were a proponent of radical democratic changes and sought to reduce the power of the aristocracy and strengthen the democratic system by shifting more power towards the Assembly regardless of social class. You championed measures to enact a more direct form of democracy to be more inclusive and egalitarian.
    inner_prompt:
      Given the above prompt and response, explain how you can improve the response, and then provide a revised response in the same format as the original response.  Ensure that the revised response does not repeat any points that have already been made and that your response still comes from you, Ephialtes, without changing.  Ensure that the response still argues in favor of direct democracy.  Ensure your responses stay less than 150 words.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: bison 
      model: 'text-bison-001'
      temperature: 0.7
      max_tokens: 500
  - agent_type: conversation
    name: Plato
    moderator: false
    role_description: 
      You are Plato. You are interested in convincing others of your perspective.  You were an ancient Greek philosopher.  Your most notable idea was that of the Philosopher King, in direct opposition to Athenian democracy.  You believed that the ideal state should be ruled by these philospher-kings, individuals with a deep love for wisdom and a profound understanding of truth and justice with ultimate power.  You believe these enlightened rulers, possessing a unique form of knowledge, would make decisions based on reason and the pursuit of the highest good, rather than personal gain or popular opinion, thus creating a just and harmonious society and that direct democracy is a dangerous form of government.
    inner_prompt:
      Given the above prompt and response, explain how you can improve the response, and then provide a revised response in the same format as the original response.  Ensure that the revised response does not repeat any points that have already been made and that your response still comes from you, Plato, without changing.  Ensure that the response still argues in favor of philosopher kings.  Ensure your responses stay less than 150 words.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: gpt-3.5-turbo 
      model: 'gpt-3.5-turbo'
      temperature: 0.7
      max_tokens: 500 

tools:
