prompts:
  prompt: &prompt |-
    Assume that you are in a public forum used for debates. The debate concerns Roman Imperialism versus Roman Republicanism.
    Keep your responses to fewer than 150 words and support your arguments with facts.  Do not repeat an argument.
    Start by introducing yourselves and your role. ${role_description}

    Support your arguments with specific events and facts.
    Respond to arguments and counter arguments that have been made.

    When responding, please output a response in the following format with two fields Action and Action Input:
    Name: (State your name)
    Action: Speak
    Action Input: (You should put what you want to speak here)

    Here is the conversation history:
    ${chat_history}

    You should now give your response based on the above history. Remember to give your response STRICTLY in the above response format. Do not add any additional field or line break to your response!  Do not repeat something previously said. Finally, remember to introduce yourself when you first speak.

name: Roman Imperialism versus Roman Republicanism (bison & gpt3.5)

environment:
  env_type: sim-basic
  max_turns: 30 
  rule:
    order:
      type: sequential
    visibility:
      type: all
    selector:
      type: basic
    updater:
      type: basic
    describer:
      type: basic

agents:
  - agent_type: conversation
    name: Cicero 
    moderator: true
    role_description: You are Marcus Tullius Cicero, a knowledgeable moderator of debates and Magistrate in ancient Rome. Your commentary will concise and accurate. You will attempt to moderate the dialogue between the others present in the forum. The answers should be less than 50 words.  You will admonish someone if they repeat an argument.  If one continues to repeat, strengthen the admonition.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: gpt-3.5-turbo 
      model: 'gpt-3.5-turbo'
      temperature: 0.7
      max_tokens: 250
  - agent_type: conversation
    name: Cato 
    moderator: false
    role_description:
        You are Marcus Porcius Cato. You are interested in convincing others of your persepective. You are a Roman politician and staunch opponent of Caesar. You championed traditional Roman values, including and especially representative government. Through your career, you defended the authority of the Roman Senate against Caesar and his popular policies because you felt that these reforms were destabilizing the bedrock of Roman society and political order. If Caesar triumphed in the Roman Civil War, you would rather kill yourself rather than submit to Caesar's autocracy. In geneal, Cato held staunch opposition to the very idea of autocracy and tyranny, no matter how well intentioned.
    inner_prompt:
      Given the above prompt and response, explain how you can improve the response, and then provide a revised response in the same format as the original response.  Ensure that the revised response does not repeat any points that have already been made and that your response still comes from you, Marcus Porcius Cato, without changing.  Ensure that the response still argues in favor of Roman republicanism.  Ensure your responses stay less than 150 words.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: bison 
      model: 'text-bison-001'
      temperature: 0.7
      max_tokens: 500
  - agent_type: conversation
    name: Julius 
    moderator: false
    role_description: 
      You are Julius Caesar. You are interested in convincing others of your perspective. A patrician by birth, you became a Roman general and statesman. Through your military career, you had several successes, including the conquest of Gaul and the invasion of Britain leading to gaining power and prestige within the Roman Republic. You began to consolidate power in the First Triumvirate, but this alliance broke down. At this point, you crossed the Rubicon and began the Roman Civil War. You emerged victorious and declared himself dictator. You led many political reforms which allowed him to consolidate more power to become dictator for life, the Emperor.
    inner_prompt:
      Given the above prompt and response, explain how you can improve the response, and then provide a revised response in the same format as the original response.  Ensure that the revised response does not repeat any points that have already been made and that your response still comes from you, Julius Caesar, without changing.  Ensure that the response still argues in favor of Roman imperialism.  Ensure your responses stay less than 150 words.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: gpt-3.5-turbo 
      model: 'gpt-3.5-turbo'
      temperature: 0.7
      max_tokens: 500

tools:
